A Rails form web page created through with various methods
ikraamg/re-former pull request #1
Opened 2020-05-13 12:25 UTC by ikraamg

Good day,

Please find the Readme here.

In this project we create the necessary MVC elements to build a user form that can be created, edited and deleted.

2020-05-13 19:50 UTC, shshamim63 requested changes
## Status :point_right: Required Changes :point_left:
___
Hi @ikraamg and @alishabab :wave:
Awesome initiative, the project contains a descriptive readme. You almost completed the project. I just found an issue and that is blocking me to approve it. Let's get to it.
___
### :spades: Mandatory Changes :spades:
- You have to use the only: on your route. Please check the comment below on your routes.rb file.
- Please fix the problem related to indentation.
___
#### Please fix the above-mentioned issue and send another review request.
___
## :herb: Happy Coding :herb:
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/)

2020-05-13 19:50 UTC, shshamim63 commented on config/routes.rb
> +  resources :users
- Use the :only option to specify just the :new, :create, ;edit and :update actions in config/routes.rb ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route1.png) [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/user_route2.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))

2020-05-13 19:50 UTC, shshamim63 commented on app/views/users/show.html.erb
> +<%end%>
Fix the indentation.

2020-05-15 00:56 UTC, kobiyoyo approved these changes
# Project Approved :thumbsup:
## Hello Team,  You have done a great job with this project. :clap: ,just few changes required
- [ ] check comments below
#### You can go ahead and merge once done!!!

2020-05-15 00:56 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +      redirect_to user_path(@user)
You can  use `redirect_to @user`

2020-05-15 00:56 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +      redirect_to user_path
You can  use `redirect_to @user`

2020-05-15 00:56 UTC, kobiyoyo commented on app/views/users/new.html.erb
> +<%= form_tag("/users") do %>
lets write it this way `<%= form_tag(users_path) do %>`

2020-05-20 08:49 UTC, merged